In [2]:
import numpy as np

## Exercicio 1

In [3]:
# from numpy import 'modulo especifico'
# import numpy
# import *
# from numpy import *

## Exercicio 2

In [15]:
lista1 = np.array([-2, 4.3, 7, 9]) # Se tiver flutuante, ele transforma tudo em flutuante
tup = (8, -5, 0, 3.2) # Se tiver flutuante, ele transforma tudo em flutuante

lista2 = np.array(tup)

lista1

array([-2. ,  4.3,  7. ,  9. ])

In [16]:
lista2

array([ 8. , -5. ,  0. ,  3.2])

## Exercicio 3

In [20]:
# Se colocarmos uma string no meio da lista(array), ele vai transformar tudo em string

In [24]:
lista3 = np.array([-2, 's', 7, 9])
lista3

array(['-2', 's', '7', '9'], dtype='<U11')

In [19]:
lista1 = np.arange(10) #Cria uma lista de 10 elementos (0-9)
print(lista1, '\n')

lista2 = np.arange(1, 32, 2).reshape(4, 4) #Cria uma matriz com valores de 1 a (32-1) de 2 em 2 valores
print(lista2)

[0 1 2 3 4 5 6 7 8 9] 

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


In [25]:
lista1 = np.linspace(1, 100, 10) # de 1 a 100, contendo 10 valores
print(lista1, '\n')

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] 



## Exercicio 4

In [26]:
# Basicamente o "arange" gera valores no intervalo sem incluir o ultimo 
# Já o "linspace" gera os valores no intervalo e inclui o ultimo elemento

In [28]:
lista2 = np.empty((6,4)) # normalmente a saída é lixo de memória ou zeros
print(lista2, '\n')

lista4 = np.eye(4) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outro
print(lista4)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29060871e-306]
 [1.89146896e-307 1.37961302e-306 1.05699242e-307 8.01097889e-307]
 [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.33510679e-306]
 [2.22522597e-306 8.01097889e-307 1.42417629e-306 8.45593934e-307]
 [6.89805151e-307 9.34611148e-307 1.37961709e-306 1.42418172e-306]
 [1.37961641e-306 1.27946076e-307 8.45610231e-307 6.01347002e-154]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
lista1 = np.zeros(8) # array contendo 8 'zeros'
print (lista1)
lista2 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(lista2)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Exercicio 5

In [30]:
lista1 = np.linspace(.5, 50, 10)
print('.shape: ', lista1.shape) # imprime o formato da array
print('.size: ', lista1.size) # imprime o tamanho da array
print('.dtype: ', lista1.dtype) # imprime o tipo de dado dos elementos

.shape:  (10,)
.size:  10
.dtype:  float64


In [31]:
print('.ndim: ', lista1.ndim) # número de dimensões
print('.itemsize: ', lista1.size) # tamanho de cada elemento em bytes

.ndim:  1
.itemsize:  10
