In [164]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Exemplo 3.1

In [165]:
data = {'Nome' : ['Joao da Silva', 'Pedro Fernandes', 'Maria Freitas', 'Paula Gonçalves', 'Ana Freitas',
                  'Luiz Costa', 'Andre Souza', 'Ana Carolina chaves', 'Patricia Silva', 'Regina Lima',
                  'Alfredo Souza', 'Margarete Cunha', 'Pedro Barbosa', 'Ricardo Alves', 'Marcio Rezende'],
        'N de dep.' : [3, 1, 0, 0, 1, 3, 4, 0, 2, 2, 3, 0, 2, 0, 1]}
df = pd.DataFrame(data)
df

Nome  N de dep.
0         Joao da Silva          3
1       Pedro Fernandes          1
2         Maria Freitas          0
3       Paula Gonçalves          0
4           Ana Freitas          1
5            Luiz Costa          3
6           Andre Souza          4
7   Ana Carolina chaves          0
8        Patricia Silva          2
9           Regina Lima          2
10        Alfredo Souza          3
11      Margarete Cunha          0
12        Pedro Barbosa          2
13        Ricardo Alves          0
14       Marcio Rezende          1

#### Média

In [166]:
df['N de dep.'].mean()

1.4666666666666666

#### Moda

In [167]:
df['N de dep.'].mode()

0    0
dtype: int64

#### Mediana

In [168]:
df['N de dep.'].median()

1.0

### Atividade 3.1

In [169]:
df['salario'] = [6300, 5700, 4500, 3800, 3200, 7300, 7100,5600, 6400, 7000, 3700, 6500, 400, 5100, 4500]
df

Nome  N de dep.  salario
0         Joao da Silva          3     6300
1       Pedro Fernandes          1     5700
2         Maria Freitas          0     4500
3       Paula Gonçalves          0     3800
4           Ana Freitas          1     3200
5            Luiz Costa          3     7300
6           Andre Souza          4     7100
7   Ana Carolina chaves          0     5600
8        Patricia Silva          2     6400
9           Regina Lima          2     7000
10        Alfredo Souza          3     3700
11      Margarete Cunha          0     6500
12        Pedro Barbosa          2      400
13        Ricardo Alves          0     5100
14       Marcio Rezende          1     4500

#### Média

In [170]:
df['salario'].mean()

5140.0

#### Moda

In [171]:
df['salario'].mode()

0    4500
dtype: int64

#### Mediana

In [172]:
df['salario'].median()

5600.0

### Atividade 3.2

In [173]:
Nota = [2.9, 3.7, 3.8, 4.7, 4.9, 5.2, 5.6, 5.8, 6.0, 6.2,
        6.3, 6.3, 6.3, 6.5, 6.5, 6.6, 6.8, 6.8, 6.9, 6.9,
        7.0, 7.0, 7.1, 7.3, 7.3, 7.4, 7.4, 7.5, 7.5, 7.6,
        7.6, 7.7, 7.7, 7.9, 8.1, 8.1, 8.2, 8.2, 8.3, 8.3,
        8.4, 8.5, 8.7, 8.7, 8.8, 8.9, 9.0, 9.1, 9.4, 9.7]

notas = pd.DataFrame({'Notas': Nota})

#### Média

In [174]:
notas.mean()

Notas    7.142
dtype: float64

#### Moda

In [175]:
notas.mode()

Notas
0    6.3

#### Mediana

In [176]:
notas.median()

Notas    7.35
dtype: float64

### Atividade 3.3

### Atividade 3.4

->  ((5.5*)+(x*3)) / 5 == 6
->  11+3x == 30
->  3x == 19
->  x == 6.33...

Logo, a segunda nota tem necessariamente maior que 6.33

In [177]:
((5.5*2)+(6.4*3)) / 5

6.040000000000001

### Atividade 3.5

In [178]:
c = 5*(45-32) / 9
c

7.222222222222222

Logo, a temperatura em celcius é de 7.22

### Atividade 3.6

In [179]:
a = np.array([0, 5, 10, 15, 20, 25])
b = np.array([5, 10, 15, 20, 25, 30])
Freq_i= np.array([5, 15, 22, 18, 12, 8])
freq_r = np.array([6.25, 18.75, 27.50, 22.50, 15.00, 10.00])
acumulada_i = np.array([5, 20, 42, 60, 72, 80])
acumulada_r = np.array([6.25, 25.00, 52.50, 75.00, 90.00, 100.00])

In [180]:
q = freq_r/100
q

array([0.0625, 0.1875, 0.275 , 0.225 , 0.15  , 0.1   ])

In [181]:
classes = []
c = ""
for i in range (len(a)):
    c = str(a[i]) + ' |-- ' + str(b[i])
    classes.append(c)
classes

['0 |-- 5', '5 |-- 10', '10 |-- 15', '15 |-- 20', '20 |-- 25', '25 |-- 30']

In [182]:
def media_classes(x, y):
    arr_media = []
    for i in range(len(x)):
        g = (x[i] + y[i]) / 2
        arr_media.append(g)
    return arr_media

In [183]:
dados = {'Classes' : classes,
       'Freq Absoluta' : Freq_i,
       'Freq Relativa' : freq_r, 
       'Acumulada Absoluta' : acumulada_i, 
       'Acumulada Relativa' : acumulada_r}
df2 = pd.DataFrame(dados)
df2

Classes  Freq Absoluta  Freq Relativa  Acumulada Absoluta  \
0    0 |-- 5              5           6.25                   5   
1   5 |-- 10             15          18.75                  20   
2  10 |-- 15             22          27.50                  42   
3  15 |-- 20             18          22.50                  60   
4  20 |-- 25             12          15.00                  72   
5  25 |-- 30              8          10.00                  80   

   Acumulada Relativa  
0                6.25  
1               25.00  
2               52.50  
3               75.00  
4               90.00  
5              100.00

#### Ponto medio classes

In [184]:
med = media_classes(a, b)
med

[2.5, 7.5, 12.5, 17.5, 22.5, 27.5]

#### Média 

In [185]:
test = []
for i in range(len(med)):
    u = med[i]*q[i]
    test.append(u)
test

[0.15625, 1.40625, 3.4375000000000004, 3.9375, 3.375, 2.75]

In [186]:
soma = 0
for i in test:
    soma += i
soma

15.0625

### Atividade 3.7

In [187]:
x = np.array([4, 6, 8, 10, 12])
y = np.array([6, 8, 10, 12, 14])
freq = np.array([10, 12, 18, 6, 4])

In [188]:
classes = []
c = ""
for i in range (len(x)):
    c = str(x[i]) + ' |-- ' + str(y[i])
    classes.append(c)
classes

['4 |-- 6', '6 |-- 8', '8 |-- 10', '10 |-- 12', '12 |-- 14']

In [189]:
dados1 = {'Classes' : classes,
         'Frequencia' : freq}

df3 = pd.DataFrame(dados1)

In [190]:
fr = freq*100/len(df3['Frequencia'])
fr

array([200., 240., 360., 120.,  80.])

In [198]:
m = fr/10

In [199]:
df3['Freq Relativa'] = m
df3

Classes  Frequencia  Freq Relativa
0    4 |-- 6          10           20.0
1    6 |-- 8          12           24.0
2   8 |-- 10          18           36.0
3  10 |-- 12           6           12.0
4  12 |-- 14           4            8.0

#### Pontos medio calsses

In [194]:
o = media_classes(x, y)
o

[5.0, 7.0, 9.0, 11.0, 13.0]

In [201]:
l = m/100
l

array([0.2 , 0.24, 0.36, 0.12, 0.08])

#### Média

In [203]:
arr = []
for i in range(len(o)):
    p = o[i]*l[i]
    arr.append(u)
arr

[2.75, 2.75, 2.75, 2.75, 2.75]

In [205]:
som = 0
for i in arr:
    som += i
som

13.75